---
- name: Enable multiverse repo  # noqa: no-changed-when
  ansible.builtin.shell: |
    apt-add-repository multiverse
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install VirtualBox Guest Additions
  ansible.builtin.apt:
    name: virtualbox-guest-dkms
    state: present
  become: true
