---
- name: Install open-vm-tools on RHEL
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 8
  ansible.builtin.dnf:
    name: open-vm-tools
    state: present
  become: true

- name: Update apt cache
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install open-vm-tools on Debian
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: open-vm-tools
    state: present
  become: true
