---
virtualbox_version_url: http://download.virtualbox.org/virtualbox/LATEST.TXT
virtualbox_latest_version: "{{ lookup('ansible.builtin.url', virtualbox_version_url, split_lines=False) | trim }}"
macos_vmware_tools_iso: "/Applications/VMware Fusion.app/Contents/Library/isoimages/x86_x64/darwin.iso"
remote_macos_vmware_tools_iso: "/tmp/vwmare-tools.iso"
