---
- name: Install qemu-guest-agent on RHEL
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8
  ansible.builtin.dnf:
    name: qemu-guest-agent
    state: present
  become: true

- name: Update apt cache
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install qemu-guest-agent on Debian
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  become: true
